version: '3.7'

services:
  listit-lol-frontend:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - .:/home/node/listit-lol
      - /home/node/listit-lol/frontend/.pnpm-store
      - /home/node/listit-lol/frontend/.cache
      - /home/node/listit-lol/frontend/build
      - /home/node/listit-lol/frontend/node_modules
      - /home/node/listit-lol/frontend/public/build
    entrypoint: ['/bin/bash']
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
      - 3001:3001
