version: '3.7'

services:
  listit-lol-frontend:
    image: node:21-bookworm-slim
    volumes:
      - ./frontend:/home/node/frontend
      - /home/node/frontend/tutorial/node_modules
    entrypoint: ['/bin/bash']
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
      - 3001:3001
